// MENU MADE — shared type schema.

export interface MenuItem {
  id: string;
  name: string;          // factual dish reference (matches menu wording)
  note: string;          // OUR paraphrase, never verbatim from source
  spicy?: boolean;
  hero?: boolean;
  source_excerpt?: string;
}

export interface MenuSection {
  name: string;
  items: MenuItem[];
}

export interface ExtractedMenu {
  restaurant_name: string;
  restaurant_city?: string;
  cuisine?: string;
  source_url: string;
  source_format: 'html' | 'pdf' | 'image' | 'spa';
  extracted_at: string;
  sections: MenuSection[];
  notes?: string[];
}

export interface SearchResult {
  name: string;
  city?: string;
  url: string;
  snippet?: string;
}

// Restaurant overview (Google-Maps-style summary card)
export interface RestaurantRating {
  score: number;
  source: string;
  count?: number;
}

export interface RestaurantOverview {
  name: string;
  address?: string | null;
  city?: string | null;
  country?: string | null;
  cuisine?: string | null;
  price_range?: string | null;
  rating?: RestaurantRating | null;
  description?: string | null;
  highlights?: string[];
  chef?: string | null;
  phone?: string | null;
  website?: string | null;
  images?: string[];
  // Google Places enrichment (optional; populated when GOOGLE_MAPS_API_KEY is set)
  place_id?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  business_status?: string | null;       // OPERATIONAL | CLOSED_TEMPORARILY | CLOSED_PERMANENTLY
  google_maps_uri?: string | null;       // Deeplink to the Google Maps page
  regional_map_url?: string | null;      // Static map at zoom ~5 (country/region)
  street_map_url?: string | null;        // Static map at zoom ~17 (street level)
  booking_url?: string | null;           // OpenTable search deeplink
}

// Recipe schema

export interface GlanceCell {
  label: string;
  value: string;
  sub: string;
}

export interface Ingredient {
  label: string;
  qty: string;
}

export interface ShoppingGroup {
  group: string;
  items: string[];
}

export interface TimelineStep {
  time: string;
  actual?: string;
  text: string;
}

export interface MethodStep {
  title: string;
  text: string;
  tip?: string;
  time?: string;     // e.g. "10 min", "5–7 min", "30 sec" — approximate wall-clock duration of the step
}

export interface Plating {
  visual: string[];
  table: string[];
}

export interface Pairing {
  type: string;
  style: string;
  title: string;
  text: string;
}

export interface RecipeParams {
  guests: number;
  skill: 'Beginner' | 'Intermediate' | 'Advanced';
  cookingTime: string;
  equipment: string[];
  dietary: string[];
  style: string;
}

export interface GeneratedRecipe {
  dish_id: string;
  dish_name: string;
  restaurant_name: string;
  servings: number;
  skill: string;
  style: string;
  total_time: string;
  hero_line: string;        // "Here is our recreated version of this …"
  intro: string;
  disclaimer: string;       // ALWAYS reinjected at serve time
  glance: GlanceCell[];
  ingredients: Ingredient[];
  shopping: ShoppingGroup[];
  timeline: TimelineStep[];
  method: MethodStep[];
  plating: Plating;
  pairings: Pairing[];
}

// The non-negotiable disclaimer text — reinjected at serialise time
// regardless of what the LLM outputs.
export const DISCLAIMER =
  "This is an original home-cookable recreation generated by MENU MADE, " +
  "inspired by a publicly listed menu reference. It is not the restaurant's " +
  "recipe. We are not affiliated with, sponsored by, or endorsed by the " +
  "restaurant.";
